### ISSUE TITLE
C++17 compatibility

### ISSUE THREAD

**Issue by JoelLinn** [xenia-project/xenia#1546]
Compiling with C++ standard version 17 or latest yields these issues (MSVC):

- [x] `yaml-cpp` in it's outdated form does not support it. Unneeded, can be removed. #1544
- [x] use of `binary_function` template which is removed. #1545
- [ ] string conversions (`utf-8` <-> `utf-16`) using deprecated `<codecvt>` header. _Can be replaced by platform specific functions (`MultiByteToWideChar()`, `iconv()` and friends) or by introducing `ICU` library or any similar one._ Discussed seperately in #1547

**Comment by gibbed** [comment]
@CookiePLMonster has suggested [utfcpp](https://github.com/nemtrif/utfcpp) and it looks like a solid choice to replace codevt/any other string conversion  usage we have.

**Comment by JoelLinn** [comment]
Can anybody come up with any downsides of forcing the whole project to C++17 early (before it is msvc/clang default)?
The added features would be beneficial in many places, for example it would make sense to make use of `std::string_view` for the string refactoring #1547

**Comment by gibbed** [comment]
Resolved with the merge of #1554.
