### ISSUE TITLE
Tony hawk Proving ground in XENIA (EPIC Photo 2 Mission ISSUE)

### ISSUE THREAD

**Issue by SebastianTripolone** [xenia-project/xenia#2225]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

i have the problem about the mission in Tony hawk's proving ground, when i'm taking those 3 photos getting visibility of the Sponsor's t-shirt, it's getting me F and i can't even pass the mission, is that problem of my skill or there's any BUG in that game?.. i hope you can help me, thank you..

[https://www.youtube.com/watch?v=s84c2gMbQIk ](url)

### Describe what should happen

....

**Comment by Masamune3210** [comment]
wrong repo, game compatibility issues go in https://github.com/xenia-project/game-compatibility
